document.addEventListener("DOMContentLoaded",()=>{
const lock=document.getElementById("lockScreen"),site=document.getElementById("site"),form=document.getElementById("passwordForm"),input=document.getElementById("password"),msg=document.getElementById("passwordMessage"),show=document.getElementById("showPassword");
show.addEventListener("click",()=>{const visible=input.type==="text";input.type=visible?"password":"text";show.textContent=visible?"○":"●";show.setAttribute("aria-label",visible?"Wachtwoord tonen":"Wachtwoord verbergen")});
form.addEventListener("submit",e=>{e.preventDefault();if(input.value==="2009"){msg.textContent="";lock.classList.add("hidden");site.classList.add("visible");document.body.classList.remove("locked");window.scrollTo(0,0);setTimeout(()=>document.querySelectorAll(".reveal").forEach((el,i)=>setTimeout(()=>el.classList.add("visible"),i*30)),450);makeHeartBurst(18)}else{msg.textContent="Dat is hem niet... probeer het nog eens ♥";input.value="";input.focus();input.animate([{transform:"translateX(-7px)"},{transform:"translateX(7px)"},{transform:"translateX(-5px)"},{transform:"translateX(0)"}],{duration:280})}});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>observer.observe(x));

const start=new Date("2026-03-20T00:00:00"),now=new Date();const days=Math.max(0,Math.floor((now-start)/86400000));document.getElementById("daysTogether").textContent=days;
const reasons=["Je kunt van een gewone dag iets bijzonders maken.","Je laat me altijd lachen, zelfs als ik daar totaal niet op zit te wachten.","Bij jou kan ik gewoon mezelf zijn.","Je onthoudt kleine dingen waarvan ik niet eens verwacht dat je ze onthoudt.","Je lach maakt eigenlijk alles meteen beter.","Met jou voelen zelfs de meest normale momenten speciaal.","Omdat jij gewoon... jij bent. ♥"];
let ri=0;document.getElementById("reasonButton").addEventListener("click",()=>{ri=(ri+1)%reasons.length;document.getElementById("reasonNumber").textContent=String(ri+1).padStart(2,"0");const t=document.getElementById("reasonText");t.animate([{opacity:0,transform:"translateY(8px)"},{opacity:1,transform:"translateY(0)"}],{duration:350});t.textContent=reasons[ri];makeHeartBurst(4)});

const lightbox=document.getElementById("lightbox");document.querySelectorAll(".memory-card").forEach(card=>card.addEventListener("click",()=>{document.getElementById("lightboxTitle").textContent=card.dataset.title;document.getElementById("lightboxText").textContent=card.dataset.text;lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false")}));const close=()=>{lightbox.classList.remove("open");lightbox.setAttribute("aria-hidden","true")};document.getElementById("closeLightbox").addEventListener("click",close);lightbox.addEventListener("click",e=>{if(e.target===lightbox)close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});

document.querySelectorAll(".future-list input").forEach((box,i)=>{const key="mirthe-future-"+i;box.checked=localStorage.getItem(key)==="1";box.addEventListener("change",()=>localStorage.setItem(key,box.checked?"1":"0"))});

const song=document.getElementById("ourSong"),music=document.getElementById("musicButton"),play=document.getElementById("musicPlayButton");function toggleSong(){if(song.paused){song.play().then(()=>{music.classList.add("playing");play.innerHTML="Pauzeren <span>Ⅱ</span>"}).catch(()=>{alert("Voeg je liedje toe als assets/song.mp3 en probeer het daarna opnieuw ♥")})}else{song.pause();music.classList.remove("playing");play.innerHTML="Speel ons liedje <span>♫</span>"}}music.addEventListener("click",toggleSong);play.addEventListener("click",toggleSong);song.addEventListener("ended",()=>{music.classList.remove("playing");play.innerHTML="Speel ons liedje <span>♫</span>"});

const secret=document.getElementById("secretReveal");document.getElementById("secretButton").addEventListener("click",()=>{secret.classList.add("open");secret.setAttribute("aria-hidden","false");setTimeout(()=>secret.scrollIntoView({behavior:"smooth"}),80);setTimeout(()=>secret.querySelector(".reveal").classList.add("visible"),300);makeHeartBurst(20)});

function makeHeartBurst(count=12){const holder=document.getElementById("hearts");for(let i=0;i<count;i++){const h=document.createElement("span");h.className="floating-heart";h.textContent=Math.random()>.25?"♥":"✦";h.style.left=(35+Math.random()*30)+"%";h.style.top=(45+Math.random()*15)+"%";h.style.fontSize=(9+Math.random()*15)+"px";h.style.animationDelay=(Math.random()*.8)+"s";holder.appendChild(h);setTimeout(()=>h.remove(),6000)}}input.focus();
});