document.addEventListener("DOMContentLoaded",()=>{document.body.classList.add("locked");
const lock=document.getElementById("lockScreen"),site=document.getElementById("site"),form=document.getElementById("passwordForm"),input=document.getElementById("password"),msg=document.getElementById("passwordMessage"),show=document.getElementById("showPassword");
show.addEventListener("click",()=>{const visible=input.type==="text";input.type=visible?"password":"text";show.textContent=visible?"○":"●";show.setAttribute("aria-label",visible?"Show password":"Hide password")});
form.addEventListener("submit",e=>{e.preventDefault();if(input.value==="2009"){msg.textContent="";lock.classList.add("hidden");site.classList.add("visible");document.body.classList.remove("locked");window.scrollTo(0,0);setTimeout(()=>document.querySelectorAll(".reveal").forEach((el,i)=>setTimeout(()=>el.classList.add("visible"),i*35)),500);makeHeartBurst()}else{msg.textContent="Not quite... try again ♥";input.value="";input.focus();input.animate([{transform:"translateX(-7px)"},{transform:"translateX(7px)"},{transform:"translateX(-5px)"},{transform:"translateX(0)"}],{duration:280});}});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>observer.observe(x));
const reasons=["The way you can make an ordinary day feel special.","Your smile. It genuinely makes everything a little better.","How easy it is to be myself around you.","The little things you remember that I don't expect you to.","Your laugh — especially when something is really, really stupid.","The fact that somehow, six months already feels like a collection of forever-memories.","Just... you. I don't think I need a better reason than that."];
let ri=0;document.getElementById("reasonButton").addEventListener("click",()=>{ri=(ri+1)%reasons.length;document.getElementById("reasonNumber").textContent=String(ri+1).padStart(2,"0");const t=document.getElementById("reasonText");t.animate([{opacity:0,transform:"translateY(8px)"},{opacity:1,transform:"translateY(0)"}],{duration:350});t.textContent=reasons[ri];makeHeartBurst(3)});
document.querySelectorAll(".memory-card").forEach(card=>card.addEventListener("click",()=>{document.getElementById("lightboxTitle").textContent=card.dataset.title;document.getElementById("lightboxText").textContent=card.dataset.text;document.getElementById("lightbox").classList.add("open");document.getElementById("lightbox").setAttribute("aria-hidden","false")}));
const close=()=>{document.getElementById("lightbox").classList.remove("open");document.getElementById("lightbox").setAttribute("aria-hidden","true")};document.getElementById("closeLightbox").addEventListener("click",close);document.getElementById("lightbox").addEventListener("click",e=>{if(e.target.id==="lightbox")close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});
document.querySelectorAll(".future-list input").forEach((box,i)=>{const key="mirthe-future-"+i;box.checked=localStorage.getItem(key)==="1";box.addEventListener("change",()=>localStorage.setItem(key,box.checked?"1":"0"))});
function makeHeartBurst(count=12){const holder=document.getElementById("hearts");for(let i=0;i<count;i++){const h=document.createElement("span");h.className="floating-heart";h.textContent=Math.random()>.25?"♥":"✦";h.style.left=(35+Math.random()*30)+"%";h.style.top=(45+Math.random()*15)+"%";h.style.fontSize=(9+Math.random()*15)+"px";h.style.animationDelay=(Math.random()*.8)+"s";holder.appendChild(h);setTimeout(()=>h.remove(),6000)}}
let musicOn=false;document.getElementById("musicButton").addEventListener("click",()=>{musicOn=!musicOn;document.getElementById("musicButton").classList.toggle("playing",musicOn);if(musicOn)alert("Add your song as assets/song.mp3 and an audio element in index.html when you are ready ♥");});
input.focus();
});